version: '3.4'

services:
  catalogdb:
    image: mongo:latest

  basketdb:
    image: redis:alpine

  discountdb:
    image: postgres:latest

  pgadmin:
    image: dpage/pgadmin4:latest

  portainer:
    image: portainer/portainer-ce:latest

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.api/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:
